import 'package:einspect/core/database/tables/database_table.dart';

/// Schema definition and business rules for the offline inspection queue.
///
/// Handles local persistence for field inspections, supporting offline-first
/// workflows, idempotency guarantees, draft management, and synchronization tracking.
final class InspectionsTable extends DatabaseTable {
  @override
  String get tableName => 'inspections';

  // UUID generated by the client used as the primary key to ensure API idempotency
  static const String columnClientId = 'client_id';

  // Remote ID assigned by the backend upon successful synchronization
  static const String columnServerId = 'server_id';

  static const String columnUserId = 'user_id';
  static const String columnWorkOrderId = 'work_order_id';
  static const String columnObservation = 'observation';
  static const String columnCondition = 'condition';
  static const String columnLatitude = 'latitude';
  static const String columnLongitude = 'longitude';

  // Local filesystem path of the evidence image stored on the device
  static const String columnPhotoPath = 'photo_path';

  // Sync lifecycle state: 'draft', 'pending', 'synced', or 'failed'
  static const String columnStatus = 'status';

  // Human-readable error message stored when a sync attempt fails
  static const String columnFailureReason = 'failure_reason';

  // ISO-8601 timestamp representing the exact moment data was collected in the field
  static const String columnCapturedAt = 'captured_at';

  // ISO-8601 timestamp recording when the remote server acknowledged creation
  static const String columnSyncedAt = 'synced_at';

  static const String columnCreatedAt = 'created_at';
  static const String columnUpdatedAt = 'updated_at';

  @override
  String get createTableQuery =>
      '''
    CREATE TABLE $tableName (
      -- Primary key relies on client-generated UUID to prevent duplicated submissions
      $columnClientId TEXT PRIMARY KEY,
      $columnServerId TEXT,
      $columnUserId TEXT NOT NULL,
      $columnWorkOrderId TEXT NOT NULL,
      -- Field data columns remain nullable to allow saving incomplete drafts
      $columnObservation TEXT,
      $columnCondition TEXT,
      $columnLatitude REAL,
      $columnLongitude REAL,
      $columnPhotoPath TEXT,
      -- Enforces strict lifecycle state transitions at the database level
      $columnStatus TEXT NOT NULL CHECK ($columnStatus IN ('draft', 'pending', 'synced', 'failed')),
      $columnFailureReason TEXT,
      $columnCapturedAt TEXT,
      $columnSyncedAt TEXT,
      $columnCreatedAt TEXT NOT NULL,
      $columnUpdatedAt TEXT NOT NULL
    )
  ''';

  @override
  List<String> get createIndicesQueries => [
    // Optimizes background worker queries that poll for pending and failed sync batches
    'CREATE INDEX idx_inspections_status ON $tableName ($columnStatus)',
    // Optimizes inspection history lookups filtered by parent work order
    'CREATE INDEX idx_inspections_work_order ON $tableName ($columnWorkOrderId)',
  ];
}
